apiVersion: v1
kind: Secret
metadata:
  name: apikey
#  type: Opaque
data:
  id: YXNh
  key: YUJjRDEyMw==

# base64 encoding
# $ echo -n "asa" | base64
# YXNh
# $ echo -n "aBcD123" | base64
# YUJjRDEyMw==

