# test_pod.yaml
#  * Draft: 2020-08-13 (Thu)
#
# Introduction to YAML: Creating a Kubernetes deployment, Nick Chase, 2020-03-11
#   https://www.mirantis.com/blog/introduction-to-yaml-creating-a-kubernetes-deployment/
# Usage:
#   $ kubectl create -f test_pod.yaml 
#   pod/rss-site created
#   $
---
apiVersion: v1
kind: Pod
metadata:
  name: rss-site
  labels:
    app: web
spec:
  containers:
    - name: front-end
      image: nginx
      ports:
        - containerPort: 80
    - name: rss-reader
      image: nickchase/rss-php-ngnix:v1
      ports:
        - containerPort: 88
